#include "../include/ui_test/controlitem.hpp"
int l_state_flag_ = 0;
int state_flag_ = 0;
int imshow_flag_1 = 1;
int imshow_flag_2 = 1;
int start_flag_ = 0;
int forw_back_ = 0;
int left_right_ = 0;
int l_start_flag_ = 0;
int camera_1_state = 0;
int camera_2_state = 0;
int vision_hsv_state = 0;
int currentIndex = 0;
int HSV_high[21] = {
    0,
};
int HSV_low[21] = {
    0,
};
int driving_state = 0;
int psd_flag[3]={0};
int traffic_state=0;
int brown_count=0;
int yellow_count=0;
int white_count=0;
int img_id=-1;
double imu_yaw = 0;
double imu_yaw_local = 0;
double x_ = 0.0;
double z_ = 0.0;
double kp_ = 0.0;
double kd_ = 0.0;
double l_x_ = 0.0;
double l_z_ = 0.0;
double max_vel_ = 0.0;
cv::Mat line_white_mask;
cv::Mat line_yellow_mask;
cv::Mat line_red_mask;
cv::Mat tra_red_mask;
cv::Mat tra_yellow_mask;
cv::Mat tra_green_mask;
cv::Mat brown_mask;
cv::Mat frame;
cv::Mat birdeye_hsv;
cv::Mat frame_hsv;
cv::Scalar lower_l_white;
cv::Scalar upper_l_white;
cv::Scalar lower_l_yellow;
cv::Scalar upper_l_yellow;
cv::Scalar lower_l_red;
cv::Scalar upper_l_red;
cv::Scalar lower_t_red;
cv::Scalar upper_t_red;
cv::Scalar lower_t_yellow;
cv::Scalar upper_t_yellow;
cv::Scalar lower_t_green;
cv::Scalar upper_t_green;
cv::Scalar lower_brown;
cv::Scalar upper_brown;
cv::Mat red_l_mask;