set(_AMENT_PACKAGE_NAME "ui_test")
set(ui_test_VERSION "0.1.0")
set(ui_test_MAINTAINER "author <author@mail.com>")
set(ui_test_BUILD_DEPENDS "cv_bridge" "opencv" "std_msgs" "nav_msgs" "geometry_msgs" "autorace_interfaces" "sensor_msgs" "libopencv-dev")
set(ui_test_BUILDTOOL_DEPENDS "ament_cmake" "rosidl_default_generators")
set(ui_test_BUILD_EXPORT_DEPENDS "std_msgs" "nav_msgs" "geometry_msgs" "autorace_interfaces" "sensor_msgs" "libopencv-dev")
set(ui_test_BUILDTOOL_EXPORT_DEPENDS )
set(ui_test_EXEC_DEPENDS "rosidl_default_runtime" "cv_bridge" "opencv" "std_msgs" "nav_msgs" "geometry_msgs" "autorace_interfaces" "sensor_msgs" "libopencv-dev")
set(ui_test_TEST_DEPENDS "ament_lint_auto" "ament_lint_common")
set(ui_test_GROUP_DEPENDS )
set(ui_test_MEMBER_OF_GROUPS )
set(ui_test_DEPRECATED "")
set(ui_test_EXPORT_TAGS)
list(APPEND ui_test_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
